version: '2.4'

services:

  router_stats:
    build: .
    tty: true
    container_name: router_stats
    # restart always = if unhealthy re-start the container
    restart: always

    ports:
      # outside to inside
      - "8003:8003"
      - "8083:8083"
 
    env_file:
      - config.env

    healthcheck:
      test: curl --fail http://localhost:8083 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s