{
 "title": "Router Stats",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "FECS (delta) Forward Error Correction",
   "type": "graph",
   "description": " Its normal to see FEC errors on an Interleaved line and rather than anything to be too concerned about its more an indication that the Interleaving & Error Correction process is working and doing what it should.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "delta(router_fe_fecs[15m])", "legendFormat": "Far End" },
    { "expr": "delta(router_ne_fecs[15m])", "legendFormat": "Near End" }
   ]
  },
  {
   "title": "CRC total (delta)",
   "type": "graph",
   "description": "Many CRC errors in a short period of time will show a noticeable reduction in throughput speed. This can be an early indication that there is too much noise on the line and in extreme situations can lead to loss of sync (disconnection with the exchange).",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(router_fe_CRC_total[15m])",
     "legendFormat": "Far End"
    },
    {
     "expr": "delta(router_ne_CRC_total[15m])",
     "legendFormat": "Near End"
    }
   ]
  },
  {
   "title": "SES (delta) Severely Errored Seconds",
   "type": "graph",
   "description": "A Severely Errored Second is a one second period which contains 30% or more errored blocks OR several other events such as one or more OOF.\n\nNote: It has been observed that a LOS event may be preceeded by a SES if the LOS was not preceeded by a LPR event.  ie The dying gasp message appears to prevent an additional SES being recorded before an LOS.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "delta(router_fe_ses[15m])", "legendFormat": "Far End" },
    { "expr": "delta(router_ne_ses[15m])", "legendFormat": "Near End" }
   ]
  },
  {
   "title": "ES (delta) Errored Seconds",
   "type": "graph",
   "description": "A one second period of time in which either one or more coding violations occurred OR at least one Loss of Signal events occurred.\n\nIts not unusual to see occasional ES and its best looking at the broader picture. Some routers will display the ES over 15 min periods (900 seconds), therefore a couple of errored seconds will probably go un-noticed.   BT uses the ES count for its DLM.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "delta(router_fe_es[15m])", "legendFormat": "Far End" },
    { "expr": "delta(router_ne_es[15m])", "legendFormat": "Near End" }
   ]
  },
  {
   "title": "HEC Error  total (delta) Header Error Check/Correction",
   "type": "graph",
   "description": "If these errors are too high within a short period of time it will slow throughput... and could even lead to connection instability",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(router_fe_HECError_total[15m])",
     "legendFormat": "Far End"
    },
    {
     "expr": "delta(router_ne_HECError_total[15m])",
     "legendFormat": "Near End"
    }
   ]
  },
  {
   "title": "UAS (delta) Un-Available Seconds",
   "type": "graph",
   "description": "Ten consecutive SES's will trigger a UAS event, and will remove the path from use. The path will become usable again after 10 consecutive seconds with no SES.\n\nA count of UAS events can be triggered by a LOS event and will continue to accrue for each second that the system is up and the path is unavailable.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "delta(router_fe_uas[15m])", "legendFormat": "Far End" },
    { "expr": "delta(router_ne_uas[15m])", "legendFormat": "Near End" }
   ]
  },
  {
   "title": "LOF  total (delta) Loss of Frame",
   "type": "graph",
   "description": "A Loss of Frame defect is initially triggered when an Out of Frame (see OOF) condition occurs and doesn't clear for more than 3ms",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(router_fe_LOF_total[15m])",
     "legendFormat": "Far End"
    },
    {
     "expr": "delta(router_ne_LOF_total[15m])",
     "legendFormat": "Near End"
    }
   ]
  },
  {
   "title": "LOSS (delta) Loss Of Signal Seconds",
   "type": "graph",
   "description": "A one second period of time in which either one or more coding violations occurred OR at least one Loss of Signal events occurred.\n\nIts not unusual to see occasional ES and its best looking at the broader picture. Some routers will display the ES over 15 min periods (900 seconds), therefore a couple of errored seconds will probably go un-noticed.   BT uses the ES count for its DLM.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "delta(router_fe_loss[15m])", "legendFormat": "Far End" },
    { "expr": "delta(router_ne_loss[15m])", "legendFormat": "Near End" }
   ]
  },
  {
   "title": "LOF  total (delta) Loss of Frame",
   "type": "graph",
   "description": "A Loss of Frame defect is initially triggered when an Out of Frame (see OOF) condition occurs and doesn't clear for more than 3ms",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(router_fe_LOF_total[15m])",
     "legendFormat": "Far End"
    },
    {
     "expr": "delta(router_ne_LOF_total[15m])",
     "legendFormat": "Near End"
    }
   ]
  },
  {
   "title": "LOS  total (delta) Loss of Signal",
   "type": "graph",
   "description": "A couple or so LOS events may go totally un-noticed during bursty activity such as web-browsing etc. The connection should be able to cope with this momentary loss of signal with the exchange, however a high level indicates a noise problem.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(router_fe_LOS_total[15m])",
     "legendFormat": "Far End"
    },
    {
     "expr": "delta(router_ne_LOS_total[15m])",
     "legendFormat": "Near End"
    }
   ]
  },
  {
   "title": "LPR  total (delta) Loss of Power",
   "type": "graph",
   "description": "Failed re-initialisation of the DSL link due to power loss. A dying gasp message has been sucessfully sent/received.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(router_fe_LPR_total[15m])",
     "legendFormat": "Far End"
    },
    {
     "expr": "delta(router_ne_LPR_total[15m])",
     "legendFormat": "Near End"
    }
   ]
  },
  {
   "title": "LCD  total (delta) Loss of Cell Delineation",
   "type": "graph",
   "description": "A Loss of Cell Delineation defect is initially triggered when an Out of Cell Delineation (see OOCD) condition occurs and doesn't clear for more than 4ms",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(router_fe_LCD_total[15m])",
     "legendFormat": "Far End"
    },
    {
     "expr": "delta(router_ne_LCD_total[15m])",
     "legendFormat": "Near End"
    }
   ]
  },
  {
   "title": "NCD  total (delta) No Cell Delineation",
   "type": "graph",
   "description": "No Cell Delineation failure count",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(router_fe_NCD_total[15m])",
     "legendFormat": "Far End"
    },
    {
     "expr": "delta(router_ne_NCD_total[15m])",
     "legendFormat": "Near End"
    }
   ]
  }
 ]
}